-- DROP TABLE IF EXISTS Widget;
--
-- CREATE TABLE Widget (
--   id UUID  PRIMARY KEY,
--   x int NOT NULL,
--   y int NOT NULL,
--   width int NOT NULL,
--   height int NOT NULL,
--   zIndex int NOT NULL,
--   LastDTFormatted TIMESTAMP NOT NULL
-- );

INSERT INTO Widget (ID, X, Y, WIDTH, HEIGHT, Z_INDEX, LAST_FORMATTED_DATE) VALUES
  (RANDOM_UUID(), 10, 10, 30, 10, 5,CURRENT_TIMESTAMP()),
  (RANDOM_UUID(), -10, 10, 20, 10, 10,CURRENT_TIMESTAMP()),
  (RANDOM_UUID(), 10, -10, 10, 20, 20,CURRENT_TIMESTAMP()),
  (RANDOM_UUID(), -10, -10, 30, 30, 30,CURRENT_TIMESTAMP());